"""Add role to users table

Revision ID: 481899481246
Revises: efbd289e3144
Create Date: 2026-04-04 21:48:25.265566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "481899481246"
down_revision: Union[str, Sequence[str], None] = "efbd289e3144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("USER", "ADMIN", name="role").create(op.get_bind())
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", name="role"),
            server_default="USER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    sa.Enum("USER", "ADMIN", name="role").drop(op.get_bind())
    # ### end Alembic commands ###
