"""ON UPDATE DELETE CASCADE in resume table

Revision ID: 53fa693c6e84
Revises: 9ada015ea930
Create Date: 2026-03-10 10:35:06.942019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "53fa693c6e84"
down_revision: Union[str, Sequence[str], None] = "9ada015ea930"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("resume_worker_id_fkey"), "resume", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "resume",
        "worker",
        ["worker_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resume", type_="foreignkey")
    op.create_foreign_key(
        op.f("resume_worker_id_fkey"),
        "resume",
        "worker",
        ["worker_id"],
        ["id"],
    )
    # ### end Alembic commands ###
