"""Create workers table

Revision ID: 72a166fe8935
Revises:
Create Date: 2026-03-05 12:28:24.903079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "72a166fe8935"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "registration_date", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "city",
            sa.Enum(
                "MOSCOW",
                "SPB",
                "NOVOSIBIRSK",
                "EKATERINBURG",
                "KAZAN",
                "NIZHNY_NOVGOROD",
                "CHELYABINSK",
                "SAMARA",
                "OMSK",
                "ROSTOV_ON_DON",
                "UFA",
                "KRASNOYARSK",
                "VORONEZH",
                "PERM",
                "VOLGOGRAD",
                "KRASNODAR",
                "SARATOV",
                "TYUMEN",
                "TOLYATTI",
                "BARNAUL",
                "IZHEVSK",
                "KHABAROVSK",
                "ULYANOVSK",
                "IRKUTSK",
                "VLADIVOSTOK",
                "YAROSLAVL",
                "ORENBURG",
                "TOMSK",
                "KEMEROVO",
                "RYAZAN",
                "NABEREZHNYE_CHELNY",
                "ASTRAKHAN",
                "PENZA",
                "LIPETSK",
                "KIROV",
                "CHEBOKSARY",
                "KALININGRAD",
                "BRYANSK",
                "KURSK",
                "IVANOVO",
                "MAGNITOGORSK",
                "U_UDE",
                "TVER",
                "STAVROPOL",
                "MINSK",
                "ALMATY",
                "ASTANA",
                "TASHKENT",
                "EREVAN",
                "TBILISI",
                name="city",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE_SEARCH", "LOOKING_AROUND", "NOT_LOOKING", name="status"
            ),
            nullable=False,
        ),
        sa.Column(
            "specialization",
            sa.Enum(
                "SOFTWARE_DEVELOPMENT",
                "DATA_SCIENCE",
                "DEVOPS_INFRASTRUCTURE",
                "TESTING_QA",
                "CYBERSECURITY",
                "DESIGN_UX",
                "MARKETING_ADVERTISING",
                "CONTENT_CREATION",
                "PRODUCT_PROJECT_MGMT",
                "ADMINISTRATION_OFFICE",
                "HUMAN_RESOURCES",
                "BUSINESS_STRATEGY",
                "SALES_BUSINESS_DEV",
                "CUSTOMER_SERVICE",
                "E_COMMERCE",
                "FINANCE_ACCOUNTING",
                "LEGAL_SERVICES",
                "BANKING_INVESTMENTS",
                "MANUFACTURING_PRODUCTION",
                "ENGINEERING_CONSTRUCTION",
                "ENERGY_MINING",
                "LOGISTICS_TRANSPORT",
                "PROCUREMENT_SUPPLY",
                "EDUCATION_ACADEMIA",
                "HEALTHCARE_PHARMA",
                "HOSPITALITY_RETAIL",
                "AGRICULTURE",
                "SECURITY_PROTECTION",
                "GOVERNMENT_NONPROFIT",
                "OTHER",
                name="specialization",
            ),
            nullable=True,
        ),
        sa.CheckConstraint("age >= 18 AND age <= 110", name="check_age"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worker")
    # ### end Alembic commands ###
