"""Resume table

Revision ID: 9ada015ea930
Revises: 72a166fe8935
Create Date: 2026-03-06 12:17:33.306028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ada015ea930"
down_revision: Union[str, Sequence[str], None] = "72a166fe8935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("about_me", sa.String(length=1000), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column("salary_expectations", sa.Integer(), nullable=True),
        sa.Column("portfolio_url", sa.String(), nullable=True),
        sa.Column(
            "education",
            sa.Enum(
                "SECONDARY",
                "SECONDARY_SPECIALIZATED",
                "INCOMPLETE_HIGHER",
                "BACHELOR",
                "MASTER",
                "CANDIDATE_OF_SCIENCES",
                "DOCTOR_OF_SCIENCES",
                name="education",
            ),
            nullable=False,
        ),
        sa.Column("education_status", sa.Boolean(), nullable=False),
        sa.Column(
            "educational_institute", sa.String(length=200), nullable=False
        ),
        sa.Column("extra_info", sa.String(length=500), nullable=True),
        sa.CheckConstraint("experience_years >= 0", name="check_exp"),
        sa.CheckConstraint("salary_expectations >= 1000", name="check_salary"),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume")
    # ### end Alembic commands ###
