"""add employer column into the vacancy table

Revision ID: aa3d6d7c298d
Revises: 21b5d757750f
Create Date: 2026-03-24 10:20:17.366075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "aa3d6d7c298d"
down_revision: Union[str, Sequence[str], None] = "21b5d757750f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacancy", sa.Column("employer", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancy", "employer")
    # ### end Alembic commands ###
