"""users table

Revision ID: cf144134d956
Revises: aa3d6d7c298d
Create Date: 2026-04-03 19:56:59.700516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cf144134d956"
down_revision: Union[str, Sequence[str], None] = "aa3d6d7c298d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("LENGTH(email) <= 200"),
        sa.CheckConstraint("LENGTH(login) >= 8 AND LENGTH(login) <= 50"),
        sa.CheckConstraint("LENGTH(password) >= 8 AND LENGTH(password) <= 50"),
        sa.CheckConstraint("LENGTH(username) >= 8 AND LENGTH(username) <= 50"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
