"""vacancy and vacancy response table

Revision ID: e1c0dfb88a13
Revises: 53fa693c6e84
Create Date: 2026-03-18 19:09:14.325357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1c0dfb88a13"
down_revision: Union[str, Sequence[str], None] = "53fa693c6e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancy",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("requirements", sa.String(), nullable=False),
        sa.Column(
            "work_format",
            sa.Enum(
                "AT_THE_EMPLOYERS_PLACE",
                "ONLINE",
                "COMBINED",
                name="workformat",
            ),
            nullable=False,
        ),
        sa.Column(
            "employment",
            sa.Enum(
                "INTERNSHIP",
                "PARTTIME_EMPLOYMENT",
                "FULLTIME_EMPLOYMENT",
                "FLEXIBLE_SCHEDULE",
                name="employment",
            ),
            nullable=False,
        ),
        sa.Column(
            "experience",
            sa.Enum(
                "NO_EXPERIENCE",
                "ONE_TO_THREE",
                "THREE_TO_SIX",
                "GREATER_THEN_SIX",
                name="experience",
            ),
            nullable=False,
        ),
        sa.Column("employer_contacts", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vacancyresponse",
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("vacancy_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancy.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "resume",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "worker",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_column("worker", "registration_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker",
        sa.Column(
            "registration_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("worker", "created_at")
    op.drop_column("resume", "created_at")
    op.drop_table("vacancyresponse")
    op.drop_table("vacancy")
    # ### end Alembic commands ###
