"""delete password check contraint

Revision ID: efbd289e3144
Revises: cf144134d956
Create Date: 2026-04-03 20:14:56.129788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "efbd289e3144"
down_revision: Union[str, Sequence[str], None] = "cf144134d956"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_password_check", "user", "check")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "user_password_check",
        "user",
        "length(password) >= 8 and length(password) <= 50",
    )
    # ### end Alembic commands ###
