"""add index on login

Revision ID: f1fdb2aeed12
Revises: 481899481246
Create Date: 2026-04-05 19:06:15.293900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f1fdb2aeed12"
down_revision: Union[str, Sequence[str], None] = "481899481246"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_login_key"), "user", type_="unique")
    op.create_index(op.f("ix_user_login"), "user", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_login"), table_name="user")
    op.create_unique_constraint(
        op.f("user_login_key"),
        "user",
        ["login"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
