from enum import Enum


class City(str, Enum):
    MOSCOW = "Москва"
    SPB = "Санкт-Петербург"
    NOVOSIBIRSK = "Новосибирск"
    EKATERINBURG = "Екатеринбург"
    KAZAN = "Казань"
    NIZHNY_NOVGOROD = "Нижний Новгород"
    CHELYABINSK = "Челябинск"
    SAMARA = "Самара"
    OMSK = "Омск"
    ROSTOV_ON_DON = "Ростов-на-Дону"
    UFA = "Уфа"
    KRASNOYARSK = "Красноярск"
    VORONEZH = "Воронеж"
    PERM = "Пермь"
    VOLGOGRAD = "Волгоград"
    KRASNODAR = "Краснодар"
    SARATOV = "Саратов"
    TYUMEN = "Тюмень"
    TOLYATTI = "Тольятти"
    BARNAUL = "Барнаул"
    IZHEVSK = "Ижевск"
    KHABAROVSK = "Хабаровск"
    ULYANOVSK = "Ульяновск"
    IRKUTSK = "Иркутск"
    VLADIVOSTOK = "Владивосток"
    YAROSLAVL = "Ярославль"
    ORENBURG = "Оренбург"
    TOMSK = "Томск"
    KEMEROVO = "Кемерово"
    RYAZAN = "Рязань"
    NABEREZHNYE_CHELNY = "Набережные Челны"
    ASTRAKHAN = "Астрахань"
    PENZA = "Пенза"
    LIPETSK = "Липецк"
    KIROV = "Киров"
    CHEBOKSARY = "Чебоксары"
    KALININGRAD = "Калининград"
    BRYANSK = "Брянск"
    KURSK = "Курск"
    IVANOVO = "Иваново"
    MAGNITOGORSK = "Магнитогорск"
    U_UDE = "Улан-Удэ"
    TVER = "Тверь"
    STAVROPOL = "Ставрополь"
    MINSK = "Минск"
    ALMATY = "Алматы"
    ASTANA = "Астана"
    TASHKENT = "Ташкент"
    EREVAN = "Ереван"
    TBILISI = "Тбилиси"


class Status(str, Enum):
    ACTIVE_SEARCH = "Активный поиск"
    LOOKING_AROUND = "Рассматриваю предложения"
    NOT_LOOKING = "Не ищу"


class Specialization(str, Enum):
    SOFTWARE_DEVELOPMENT = "Разработка ПО"
    DATA_SCIENCE = "Аналитика и Data Science"
    DEVOPS_INFRASTRUCTURE = "Инфраструктура и DevOps"
    TESTING_QA = "Тестирование (QA)"
    CYBERSECURITY = "Информационная безопасность"
    DESIGN_UX = "Дизайн и UX/UI"
    MARKETING_ADVERTISING = "Маркетинг и Реклама"
    CONTENT_CREATION = "Контент и Копирайтинг"
    PRODUCT_PROJECT_MGMT = "Управление проектами и продуктами"
    ADMINISTRATION_OFFICE = "Административный персонал"
    HUMAN_RESOURCES = "Управление персоналом (HR)"
    BUSINESS_STRATEGY = "Стратегия и Консалтинг"
    SALES_BUSINESS_DEV = "Продажи и развитие бизнеса"
    CUSTOMER_SERVICE = "Клиентский сервис и поддержка"
    E_COMMERCE = "Электронная коммерция"
    FINANCE_ACCOUNTING = "Финансы и Бухгалтерия"
    LEGAL_SERVICES = "Юридические услуги"
    BANKING_INVESTMENTS = "Банковское дело и инвестиции"
    MANUFACTURING_PRODUCTION = "Производство и Промышленность"
    ENGINEERING_CONSTRUCTION = "Инженерия и Строительство"
    ENERGY_MINING = "Энергетика и Добыча сырья"
    LOGISTICS_TRANSPORT = "Транспорт и Логистика"
    PROCUREMENT_SUPPLY = "Закупки и Снабжение"
    EDUCATION_ACADEMIA = "Образование и Наука"
    HEALTHCARE_PHARMA = "Медицина и Фармацевтика"
    HOSPITALITY_RETAIL = "Туризм, Рестораны и Ритейл"
    AGRICULTURE = "Сельское хозяйство"
    SECURITY_PROTECTION = "Безопасность и Охрана"
    GOVERNMENT_NONPROFIT = "Госслужба и НКО"
    OTHER = "Другое"


class Education(str, Enum):
    SECONDARY = "Среднее"
    SECONDARY_SPECIALIZATED = "Среднее профессиональное"
    INCOMPLETE_HIGHER = "Незаконченное высшее"
    BACHELOR = "Бакалавриат"
    MASTER = "Магистратура"
    CANDIDATE_OF_SCIENCES = "Кандидат наук"
    DOCTOR_OF_SCIENCES = "Доктор наук"


class WorkFormat(str, Enum):
    AT_THE_EMPLOYERS_PLACE = "На месте работодателя"
    ONLINE = "Онлайн"
    COMBINED = "Совмещенный"


class Employment(str, Enum):
    INTERNSHIP = "Стажировка"
    PARTTIME_EMPLOYMENT = "Частичная занятость"
    FULLTIME_EMPLOYMENT = "Полная занятость"
    FLEXIBLE_SCHEDULE = "Гибкий график"


class Experience(str, Enum):
    NO_EXPERIENCE = "Нет опыта"
    ONE_TO_THREE = "1-3 года"
    THREE_TO_SIX = "3-6 лет"
    GREATER_THEN_SIX = "Более 6 лет"
